config/routes.rb
Catpic::Application.routes.draw do
  resources :posts

  resources :pics

  resources :users

  resources :cats

  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  get 'kirjaudu', to: 'sessions#new'
  get 'signin', to: 'sessions#new'

  delete 'signout', to: 'sessions#destroy'

  root 'pics#index'

end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :user
  validates :url, presence: true
  validates :user_id, presence: true

  def to_s
    "#{header}"
  end
end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = Pic.new(pic_params)
    @pic.user = current_user

    respond_to do |format|
      if @pic.save
        format.html { redirect_to @pic, notice: 'Pic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pic }
      else
        format.html { render action: 'new' }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:user_id, :url, :header, :date, :desc, :exif)
    end
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :header %><br>
    <%= f.text_field :header, class: "form-control"  %>
  </div>
  <div class="field">
    <%= f.label :desc %><br>
    <%= f.text_field :desc, class: "form-control" %>
  </div>

  <!-- <div class="field">
    <%= f.label :exif %><br>
    <%= f.text_field :exif %>
  </div>
  commenting away for now
  !-->
  <div class="actions">
    <%= f.submit class:"btn btn-success" %>
  </div>
<% end %>

app/views/pics/edit.html.erb
<h1>Editing pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/index.html.erb
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @pics.each_with_index do |pic, index|%>
    <li data-target="#carousel-example-generic" data-slide-to="<% index %>"></li>
    <% end %>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <% @pics.each do |pic| %>
        <div class="<% if pic.equal?(@pics.first);%> active <% end %> item" style="background-size: cover; background-position: center center; background-image: url(<%= pic.url %>);height: 600px">
            <div class="carousel-caption">
                <h3><%= link_to pic.header, pic %></h3>
          </div>
        </div>
      <% end %>
  </div>

  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
</div>

app/views/pics/new.html.erb
<h1>New pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<div class="row">
  <div class="col-md-9">
      <img class="img-responsive" src="<%= @pic.url %>">
  </div>
  <div class="col-md-3">
    <strong>
      <%= @pic.header %>
    </strong> by
    <%= @pic.user %> <br>
    <strong>Description:</strong>
    <%= @pic.desc %>

    <div class="form-group">
    <% unless !current_user %>
        <% if @pic.user_id == current_user.id %>
            <%= link_to 'Edit', edit_pic_path(@pic), class:"btn btn-primary"  %>
            <%= link_to 'Remove pic', @cat, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger"  %>
        <% end %>
    <% end %>
    </div>
  </div>

</div>