config/routes.rb
Catpic::Application.routes.draw do
  resources :posts

  resources :pics

  resources :users

  resources :cats

  resources :sessions, only: [:new, :create]
  get 'signin', to: 'sessions#new'
  get 'signup', to: 'users#new'
  get 'kirjaudu', to: 'sessions#new'
  get 'signin', to: 'sessions#new'

  delete 'signout', to: 'sessions#destroy'

  root 'pics#index'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Catpic', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>


<li><%= link_to 'Cats', cats_path %></li>
<li><%= link_to 'Posts', posts_path %></li>
<li><%= link_to 'Users', users_path %></li>
<% if not current_user.nil? %>
    <li class="dropdown">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">Create<b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to 'New pic', new_pic_path %></li>
        <li><%= link_to 'New post', new_post_path %></li>
        <li><%= link_to 'Add cat', new_cat_path %></li>
      </ul>
    </li>

    <li><%= link_to current_user.name, current_user %></li>
    <li><%= link_to 'signout', signout_path, method: :delete %></li>
<% else %>
    <li><%= link_to 'signin', signin_path %></li>
    <li><%= link_to 'signup', signup_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700' rel='stylesheet' type='text/css'>
    <title><%= content_for?(:title) ? yield(:title) : "Catpic" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Catpic" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <div class="container" role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </div>
  </body>
</html>